NAME := com.sunlightweather.free.ics.ultimatesettingstoolswidget.lockscreen
APK  := $(NAME).apk

ifndef DROIDSAFE_SRC_HOME
    $(error DROIDSAFE_SRC_HOME is undefined)
endif

include $(DROIDSAFE_SRC_HOME)/android-apps/Makefile.common

