NAME := nl.nhg.android.thuisarts
APK  := $(NAME).apk

ifndef DROIDSAFE_SRC_HOME
    $(error DROIDSAFE_SRC_HOME is undefined)
endif

include $(DROIDSAFE_SRC_HOME)/android-apps/Makefile.common

